### ISSUE TITLE
Make demo player use this please , i am newbie 

### ISSUE THREAD

**Issue by Zifai** [mphe/GDNative-Ropesim#1]

**Comment by mphe** [comment]
Please formulate your question so that I can understand it. I have no idea what you mean.

**Comment by Zifai** [comment]
Like the player holding the rope to jump, and clicking right and left for the player to control the bottom of the rope, Like the game Limbo

**Comment by Zifai** [comment]
Like the player holding the rope to jump, and clicking right and left for the player to control the bottom of the rope, Like the game Limbo

**Comment by mphe** [comment]
Superseded by #6
