### ISSUE TITLE
Outdated macOS build

### ISSUE THREAD

**Issue by cadence-s** [mphe/GDNative-Ropesim#3]
The macOS build currently only targets x86_64 architecture. Adding an arm64 binary or replacing the current x86_64 binary with Universal 2 is necessary for it to run on macs from 2021 onwards.

**Comment by mphe** [comment]
Thanks for the heads up, I've updated the build script.
Can you try the [most recent](https://github.com/mphe/GDNative-Ropesim/actions/runs/7567646550) build if it works for you?
I'm not a mac user, so I can't really test it myself.

**Comment by mphe** [comment]
I assume this is fixed with 21c1c81360421d5332f56d07c7580a7e6ed3c1f6.
