### ISSUE TITLE
NodeRopeServer not found on mac 

### ISSUE THREAD

**Issue by Tacoao** [mphe/GDNative-Ropesim#7]

**Comment by Tacoao** [comment]
res://addons/ropesim/Rope.gd:125 - Parse Error: Identifier "NativeRopeServer" not declared in the current scope.

**Comment by mphe** [comment]
Please provide information about your system, how you installed the addon and provide a minimal reproduction project.

**Comment by Tacoao** [comment]
Im on Mac Os and and godot 4.2.2 stable-version  I downloaded the extension from the assetLib

**Comment by mphe** [comment]
There was recently an issue related to Mac version incompatibilities (#3).
Apparently I forgot to create a new release after updating the build.
Since you didn't specify which MacOS version you are using, I can only guess that you might have run into the same issue.
Please try [this version](https://github.com/mphe/GDNative-Ropesim/actions/runs/8925150114/artifacts/1467353149) from the [recent](https://github.com/mphe/GDNative-Ropesim/actions/runs/8925150114) GH Actions build and report back if it works for you.

**Comment by Tacoao** [comment]
Im on mac Os sonoma 14.4.1 and it didn't work , thank for your help i hope it will work and that we can find a solution

**Comment by Tacoao** [comment]
when im trying to open the project i have this notification Unable to open “libropesim.macos.template_debug” as developer cannot be verified. I think it could be linked ?

**Comment by Tacoao** [comment]
Thank you it worked

**Comment by mphe** [comment]
Great, then I'll create a release and the update will be on the asset store in the next few days. Until then, you can simply use these libs that worked.

Regardless of this issue, here are some friendly tips for the future:
- Please put a reasonable amount of effort when posting on Github or when asking for help in general.
- People can't read your mind and also can't tell you why something is not working without having various types of information about your system and environment.
- Hence, if you want people to help you, provide as much information about your issue as possible. This includes:
    - Version numbers of all involved software, including the OS.
    - Full logs as far as applicable, not just single lines.
    - A description of what you are trying to do
    - Code to reproduce the issue or a minimal reproduction project (MRP). An MRP is an empty project which contains just enough code to reproduce the issue and nothing more. In this case, for example, it would be a default project with the plugin installed and a single scene that contains one `Rope` node. You can then upload the project and make the life of people trying to reproduce and debug the issue much easier. An MRP becomes increasingly helpful the more complex the issue gets.
- Finally, Github issues are not a chatroom. Please do not spam messages and try to respect basic punctuation and grammar as far as possible. It's perfectly fine if you are not fluent in english, just try your best. That means, try what people suggest, provide information that was asked for (as far as possible) and write up your stuff in a single post when you're done. If you have questions or are unsure about something, just ask. Before submitting, take a moment to proof read your text. You can also edit messages when you notice you have forgot something.
